### ISSUE TITLE
Re-add cache

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#115]
But it will be disabled by default (calls in init.sqf commented out and parameter block in description.ext also commented out).

**Comment by ninjaProtocol** [comment]
Yes please.

Reasoning for wanting it back:

1. It was removed without discussion
2. BI Dynamic view distance not at feature parity afaik
3. BI DVD not proven to work reliably
4. BI DVD was found to be buggy when I tried using it last. At least some issues have been fixed but unless someone tries using it its hard to know.
5. Some want to remove F3 caching because there are not enough missions using it, and apparently none of the newer ones especially. Reason for not using it is likely due to lower session attendance of late, hence lack of large scale missions. However I do not believe that framework decisions should be made on the basis of seasonal variations in player count.

**Comment by shadow-fa** [comment]
Are we sure we want to disable this component by default?
When should missionmakers enable it?

**Comment by SamLex** [comment]
I think the general idea is for mission makers to enable it when they feel their mission is big enough to warrant it. Or when its requested during mission testing. Including it by having it disabled by default also means that if we experience an increase of players that causes caching to become necessary, we can easily retroactively enable caching on old missions in an automated fashion.
