### ISSUE TITLE
Update template with new launchers

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#136]
~~Ideas / To-Do-List for the tank DLC:~~

~~**Platoon / Vehicles**~~
~~- [ ] Expand attachment teams to 3 roles? (#167) _(open discussion)_~~
~~- [ ] Platoons - add CAS1 element? (#166) _(open discussion)_~~
~~- [ ] Use new vehicle classes (Note: New Marid doesn't have a commander seat.)~~

~~**Gear**~~
~~- [ ] Add Insignia for potentially new types of units (e.g. #166)~~
~~- [ ] reorganise aircrew classes (#165) _(open discussion)_~~
~~- [ ] Launchers (from darkChozo's post below) _(open discussion)_~~

Edit (Lexer): Since this issue has mainly devolved into talking about the launchers, I've renamed it and created issues (#167, #166, #165, #181) for the others. Insignias don't seem to be required as we only currently have them for the main infantry units (CO, DC, A, B, C, J)

@ Collaborators: Feel free to edit this text to extend the list!

**Comment by NikkoJT** [comment]
Based on the stuff released to dev branch today, I suggest the following:

> Change NATO and AAF Rifleman (AT) classes to use the new MAAWS Mk4 unguided AT
> Change CSAT MAT to use the new 9M135 Vorona ATGM

**Comment by darkChozo** [comment]
On the subject of launchers, here's a reference for what we have now on dev branch. All data is for HEAT/AT munitions and is taken directly from CfgAmmo configs. 

|Launcher|Direct Damage (hit)|Splash Damage (indirectHit)|Fire Mode|Max Range|Other Features|
|--|--|--|--|--|--|
|RPG-7|400|10 (6m)|Dumbfire|500m effective|guided by hand of Stalin|
|MAAWS Mod 0|500|15 (2m)|Dumbfire|1000m effective|High projectile velocity|
|MAAWS Mod 1|500|15 (2m)|Dumbfire|1000m effective|High projectile velocity,Laser rangefinder, NV|
|PCML|500|10 (3m)|Dumbfire, visual lock|500m lock, 1000m? dumbfire|Laser rangefinder, flyover top-attack, NV|
|RPG-42|600|20 (4m)|Dumbfire|500m effective|NV|
|Vorona|700|10 (1m)|SACLOS|2000m|Laser rangefinder, thermals|
|Titan AT|750|15 (4m)|SACLOS, IR lock|2000m|Laser rangefinder, top-attack, thermals|

From this, some observations:

The RPG-7, unsurprisingly, is weak in every way. Interestingly, it does have the largest explosive splash radius, but I have no idea if that will ever make it deal more damage than other weapons outside of contrived scenarios.

The MAAWS and RPG-42 are about on par, with the RPG-42 effectively trading range for damage. If I were to rate them, I'd probably say MAAWS mod 1 > RPG-42 > MAAWS mod 0, but I think they all make sense as the LAT for our mainline factions.

The PCML is weird, and its classification effectively hinges on how good the top attack mode. Without top attack, it's broadly comparable to the MAAWS mod 1. If the top attack makes it an effective anti-armor weapon, it might be more of a MAT weapon. My initial impression is that the top attack mode seems pretty good, but it'll take some testing.

Finally, the Titan AT effectively does everything the Vorona does, but better (at least for now). Basically, the Titan is the Vorona with the addition of fire-and-forget and top attack modes.

Based on this, my preliminary thoughts on AT armaments are:

||NATO|CSAT|AAF|FIA|Syndikat|ParaSyndikat|
|-|-|-|-|-|-|-|
|**LAT**|MAAWSmod1|RPG-42|MAAWSmod0|MAAWSmod0|RPG-7|MAAWSmod0|
|**MAT**|PCML|Vorona|PCML|PCML|RPG-42|Vorona|
|**HAT**|Titan|Titan|Titan|Titan|Vorona|Titan|

**Comment by darkChozo** [comment]
Branching from some Discord discussion:

My ideas for launcher assignments are based on the following pseudo-canon for this factions:
* NATO and CSAT are NATO and CSAT
* The AAF use a combination of sourced European equipment and stuff that NATO gave them
* The FIA mostly used stolen AAF equipment, plus some equipment sourced from the black market. MAT/HAT weapons would probably be pretty rare due to lack of proper supply chains.
* Syndikat are warlord-led bandits/militias/whatever, primarily using black market-sourced Russian weaponry but are also secretly supplied by the Chinese CSAT. Plus they have the LIM for some reason.
* Paramilitary Syndikat are basically just Syndikat+. They get better weapons through
* The Titan was handed down from on high to all the world's militaries as the one true HAT.

Also, there seems to be a consensus to add a new vehicular AT class to account for the new AT technicals and LSVs. What there isn't a consensus on is the name. Current front runners are VAT (vehicle anti tank), VMAT/VHAT (vehicle medium/heavy anti tank), and SPG (self propelled gun).

**Comment by NikkoJT** [comment]
Given that the MAAWS Mk4 has both HEAT and HE rounds, like the RPG-42, we should consider adding a second RAT magazine type in AssignGear, similar to the _HATmag2 that already exists for the Titan AP missiles.

**Comment by darkChozo** [comment]
So, the DLC has come out, and things have changed! [Here's data](https://docs.google.com/spreadsheets/d/18b9zW2IjBt7DFks5SzJegIP5fZhK83RZM3Zg3OqMWgk/edit?usp=sharing) that I'm too lazy to reformat for Github. Or more practically, some quick testing data:

||RPG-7|MAAWS|RPG-42|PCML|Vorona|Titan|
|-|-|-|-|-|-|-|
|range|500m|1000m|500m|800m|2000m|2000m|
|*shots to kill*|||||||
|vs. wheeled IFV|1-3|1-2|1-2|1-3|1|1|
|vs. tracked IFV|1-7|1-4|1-3|1-3|1|1-2|
|vs. T-100|8-20+|3-4|2-6|8-?|2|2-4|

Couple notes. The PCML is weird because it's a low-ish penetration projectile that attacks from above, which means that a target's top armor and general sturdiness is more important than its overall armor. Against the T-100 from the front, it looks like it was actually hitting the gun and doing no damage. Also, the Titan AT might be slightly underrepresented because I was testing at short range (<200m), where it doesn't actually have much of a top-attack profile.

Beyond that, summarizing my impressions:

**RPG-7:** The token outdated launcher. The RPG-7 is actually reasonably effective against light armor, but struggles against the heavier IFVs and is a total no-go against heavy armor. Worth noting that it's non-tandem HEAT, meaning that it's particularly ineffective against slat armor ERA. All-in-all, it's less of a joke than before, but it's still outclassed by all of the other launchers. One thing that's interesting is that it might force people to go for disabling gun shots instead of hard kills.

The RPG-7 lacks a HE rocket for some reason, though the HEAT rocket is okay against infantry. It also has adjustable sights up to 500m, which is pretty nice.

**RPG-42**: The RPG-42 hasn't changed much. It's still a short-ish range dumbfire launcher with a high arc and decent damage. The 42 kinda feels like it's outclassed by the MAAWS in general, though it does have higher penetration which might make it more reliable in borderline situations. It also has night vision, which is nice at night.

**MAAWS:** In terms of performance, the MAAWS feels a little better than the RPG-42. It has a faster projectile, a lower arc, and ranging up to 1000m, which means it's generally better at long range, though it's still difficult to hit moving targets at more than 2-300m. Practically speaking, it also does comparable damage to the 42.

The MAAWS comes in two variants with different scopes, the mod 0 and the mod 1. The mod 0 is the lower tech version, and has no special features to speak of, though it arguably has better ranging indicators than the mod 1. The mod 1 is the higher tech variant that comes with night vision and a very, very handy laser rangefinder. Overall, I'd say the MAAWS mod 1 is the best overall light launcher, while the mod 0 and RPG-42 trade places depending on whether the 42's night vision is useful or not.

**PCML:** The PCML is weird now. It has the lowest penetration of all the modern launchers, but its top-attack mode means that it almost always hits an AFV's weak top armor. That means that its effectiveness depends less on its target's armor and more on its overall ability to absorb damage. I also feel like this means that it might disable turrets and guns more often than other launchers, which makes it difficult to test out of mission conditions.

It feels like it's the only real MAT weapon, primarily due to the lock-on. This makes it fully effective up to 800m, whereas the MAAWS loses a lot of practical effectiveness beyond close range. It also weighs slightly more than the LAT launchers. On the other hand, it lacks the punch of the heavier launchers, and is generally not that great against tanks. This is an area that could really use field testing, as it's difficult to judge theoretically.

Also it has a laser rangefinder for some reason, as well as direct and dumbfire modes. Due to the low penetration (roughly on the level of the RPG-7), these modes are mostly only at all practical against lighter vehicles.

**Vorona:** The Vorona has graduated from MAT school to become a fully-fledged heavy launcher. It seems to be very effective against armor in all circumstances, one-shotting any IFV and generally taking out tanks in 1-3 shots. Compared to the Titan, it does more damage at the same range, but can only fire in SACLOS mode. The launcher is also much heavier than the Titan, meaning that a Vorona team will generally carry one less shot than a Titan team.

Similar to the Titan, it comes with a nice thermal vision mode, and it also has the highest damage HE round of all the man portable launchers. Basically, it's a Titan that trades a bit of flexibility for a bit of power.

**Titan AT:** The Titan has a nice new top-attack mode which is hard to evaluate. It has phenomenal penetration already, so unlike the PCML it likely doesn't benefit as much from hitting top armor, but it might lead to more disabling gun hits than would otherwise occur. Beyond that, the Titan AT does a bit less damage than a Vorona, but has an IR lock F&F mode. This makes it weak to countermeasures, but also frees up the AT unit to either fire another missile or get behind cover. It can also fire in SACLOS mode if you want it to do a Vorona impression.

---

So, that was a lot of words to say that things haven't changed (relatively) much. Damage on all the launchers (besides the PCML) was increased, and the Vorona was made into a proper competitor with the Titan. The main thing this changes is the fact that the Vorona is now suited to be HAT for the CSAT-y factions, which leaves their MAT slot open. The problem here is that there's not really a good CSAT MAT weapon, so we might either have to give them the PCML, or press the RPG-42 into that role as a sort of LAT-MAT team.

**Comment by NikkoJT** [comment]
Factions appear to have the correct launchers in 3.5.2 test mission.
