### ISSUE TITLE
Move Briefing>Credits to briefing.sqf

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#145]
Move Briefing>Credits to briefing.sqf to avoid duplicate code and maybe add something like the following:
```sqf
private _version = getArray (missionconfigfile >> "fa3_version");
private _versionString = "Made with FA3 version " + (_version joinString '-')
// => "Made with FA3 version 3-5-1"
```

Related to Issue #83. 
It should probably be done together with #83.

The only problem with that is, that missionmakers would have yet another place (new file) to change when creating a new mission. Maybe we can also/instead use the eden mission authorname (or the one that's sometimes set in description.ext)

**Comment by NikkoJT** [comment]
The credits section is sometimes used to credit other people for scripts or custom assets used in the mission. If credits generation is completely automatic, that would be lost.

I've no problem with centralising it, since it doesn't need to be different between sides, but it needs to keep the option to have more than just the missionmaker's name and F3 version.

**Comment by SamLex** [comment]
Yes, of course. I think there would be an area for the missionmaker to add their own credits, and then the "Made with..." would be automatically added to the end..
