### ISSUE TITLE
Expand attachment teams to 3 roles

### ISSUE THREAD

**Issue by NikkoJT** [Raptoer/F3#167]
Costno proposes adding a semi-optional third member to most attachment teams. This third soldier would act as an ammunition carrier and watchstander, as well as providing more slotting flexibility for awkward numbers.

The proposed new roles would require new assignGear classes - essentially AARs carrying specialist ammunition instead of AR mags.

This would not apply to teams with Statics (MTR, HMG, HSAM, HAT) or to the Sniper Team, since spare ammunition for statics cannot be carried and sniper teams are traditionally two-person.

Edit: some people (Chozo) suggest that the sniper team could receive a third person anyway.

**Comment by darkChozo** [comment]
A third team member seems to make the most sense in situations where the TL/assistant is actively spotting and directly fire from the gunner. If you're busy staring through binoculars downrange, it's difficult to keep an eye on your surroundings, which is where a third soldier providing security can be useful.

Under that logic, a third member makes the most sense for MMG and sniper teams. Also probably technical teams if we're into that.

It makes some sense for HMG and AT teams, who have more independent gunners but usually are pretty focused on specific directions/fields of fire.

It makes the least sense for SAMs, since they usually need 360 coverage anyway, and for mortars, since mortar gunners aren't very dependent on their spotters.

**Comment by shadow-fa** [comment]
Which (assignGear) unit type do we want to use here? Simply a normal rifleman (`r`) ?
Also, which attachment groups exactly do we want to extend?

**Comment by NikkoJT** [comment]
Attachment teams appear to be correctly expanded in 3.5.2 test mission and have the appropriate loadouts for new assistants.
