### ISSUE TITLE
FA3.5.2 (RC1) issues

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#199]
FA3.5.2 issues:
* ~~some people might not see the HALO briefing page~~
-> ~~Requires further testing~~ Potential issue found #208 
* ~~disableThermals for zeus did not seem to work for the admin that used the briefing page to become zeus.~~
-> ~~Requires further testing~~ Appears to be working as expected.
* ~~gendarme alpha team is out of order (only in test mission or also in template?) #202~~
* ~~maybe we want to switch the order of the briefing pages for `Loadout` and `Loadout Team` #200~~
* ~~Team colours aren't applied when the leader is an AI #201~~

Not bug:
* ~~assignGear vehicles: Not all trucks/IFVs/helicopters have bags.~~ Not 3.5.2 issue, #203 to change in 3.5.3

Not 3.5.2 specific / old bugs:
* ~~assignGearAI leaves units naked sometimes~~ #198

Specific to the testing mission:
* Testing briefing page might not be JIP compatible

**Comment by NikkoJT** [comment]
> What is the order in the test mission and what should it be?

It's Gendarme, Sergeant, Gendarme, Gendarme - when it should be Sergeant, Gendarme, Gendarme, Gendarme.

>"some people"???

It might have been that only team leaders could see it, but I recall we had some trouble narrowing down the cause and I'm not sure if we actually managed to figure it out.

>Which ones are missing?

I specifically recall that there were bags in the Huron, but not in the NATO IFVs and Hunters. They were reported missing from other factions too but I was only checking NATO myself.

**Comment by SamLex** [comment]
Ah ok, thanks. Created #202 to fix that.

I'm assuming this was when only the group leader could start the HALO jump? One issue I can see is that, because of the way mapClickTeleport works, the HALO briefing generation is triggered from the leaders computer, meaning it only happens once they are loaded. Might also be something weird about not being able to change the briefing whilst in the briefing screen.

Looks like bags were only ever added to medium and heavy helos, never anything else. We just fixed the bug with the name of the bag variable. Since this isn't really an issue with 3.5.2 per-se, I've created #203 for 3.5.3.

**Comment by NikkoJT** [comment]
When I tested it during the original test session, I used FA Admin Zeus to spawn the vehicle, which obviously explains why it didn't work. (I was just asked to test whether it worked for zeus-spawned vehicles - Shado didn't mention it had to be briefing-assigned in particular...)
