### ISSUE TITLE
Protect engineers from having their mines removed by SafeStart

### ISSUE THREAD

**Issue by darkChozo** [Raptoer/F3#60]
Currently, it's very easy for defensive engineers to have their explosives (inherits from MineCore, PipeBombCore, TimeBombCore, etc) be removed by SafeStart. This is because, on defensive missions, you'll often place mines at mission start, relatively close to your spawn.  Losing a mine is also way more painful than losing a bullet, since you'll typically only have a few mines.

There are a few ways of addressing this. One is to detect if a unit has mines, and display a special message to them at the start of a mission. This message should be separate from the normal SafeStart messages, so people actually notice them.

Option 2 is to use inGameUISetEventHandler to disable the UseMagazine action. This is almost perfect, except there can only be one inGameUISetEventHandler, meaning that if mission has a inGameUISetEventHandler set we will overwrite it. This means that this option only really works if it's configurable.

Option 3 is to modify the Fired EH that deletes bullets to readd an explosive magazine if it detects that the player has placed one (if they use the "Put" weapon). This is probably the best solution, but is a bit inelegant and has some possibility of infinitely duplicating magazines.

**Comment by Quailsnap** [comment]
Is there no stackable alternative for inGameUISetEventHandler?

**Comment by darkChozo** [comment]
Pretty sure no, but if there is one that I don't know about then that'd obviously be ideal.

**Comment by shadow-fa** [comment]
Currently the Safe Start component makes everyone invulnerable **and** removes all projectiles with a `Fired` Event Handler.
Is there a reason we have these Event Handlers?
They've only caused us troubles so far.
* They prevent us from engaging enemies before the safe start timer reaches zero (which can happen if we quickly move to the enemies within the first minute (1 minute is the default time, and 1 minute is the finest granularity at which to set the timer), which has happened quite a few times.
* Mines are removed because of that.
* AI projectiles are currently not removed (i think), which makes it asymmetrical and weird.

If we simply remove these Event Handlers it would solve our issues.
Or are there any downsides to this that I'm not aware of?
